### ISSUE TITLE
UI that updates user vector (TBD)

### ISSUE THREAD

**Issue by patrickhpan** [Harvard-CS96/textroulette#31]

**Comment by russellpekala** [comment]
This should not be with a form tag, should be with ajax post.  A lot more flexibility

**Comment by patrickhpan** [comment]
@russellpekala can you link to a specific file/line number? (go to the file in the viewer, click on the line number, and copy the URL once the line is highlighted, which gives you something like this: **https://github.com/Harvard-CS96/textroulette/blob/master/matcher.js#L8*)

also, i'm pretty sure this is in no way the actual UI, so whatever is fastest for @willbryk720  makes the most sense

**Comment by russellpekala** [comment]
@patrickhpan I think built in form radio buttons are annoying and hard to debug though, so I'd rather we stick with ajax.  I tried to get a post request working with form buttons and wasted like an hour.  It's more likely our final work will find ajax easier to incorporate.  It shouldn't be any harder for frontend since jquery can just use $(#q_id). value to populate a json.

**Comment by russellpekala** [comment]
https://github.com/Harvard-CS96/textroulette/blob/9523301ab57685cdaa4bf452b2dacff4fe127dbd/public/updatePreferences.html#L135

**Comment by russellpekala** [comment]
Also @jacoblurye Can you copy the relevant js into your new handlebars file for updatePreferences.html, and then delete the plain html one?

**Comment by patrickhpan** [comment]
ideally we won't be using jQuery at all once we start building the actual UI created by design team
